import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [ARRmonthly, setARRmonthly] = useState(0);
  const [convRate, setConvRate] = useState(0);
  const [LTVinMonths, setLTVinMonths] = useState(0);


  return (
    <div className='default'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className='row'>

        <div className='col left-side'>
          <div className='main-calc'>


            <div className='calculator-line'>
              <div className='row'>
                <div className='col value-heading'>
                  Average deal size (monthly recurring revenue) in AUD

                </div>
                <input className='col' type="text" name="name"  onInput={e => setARRmonthly(e.target.value)}/>
              </div>
            </div>

            <div className='calculator-line'>
              <div className='row'>
                <div className='col value-heading'>
                  Average demo to close {<br />}
                  conversion rate

                </div>
                <input className='col' type="text" name="name" onInput={e => setConvRate(e.target.value)}/>
              </div>
            </div>

            <div className='calculator-line'>
              <div className='row'>
                <div className='col value-heading'>
                  Average lifetime value of {<br />}a

                  client

                </div>
                <input className='col' type="text" name="name" onInput={e => setLTVinMonths(e.target.value)}/>
              </div>
            </div>


            <div className='row'>

            </div>

          </div>
        </div>

        <div className='col right-side'>
          <div className='roi-result'>
            {calcRoi()}% ROI
            <div className='roi-card'>
              Persifi will generate approximately ${calcMRR()} in monthly recurring revenue, a total of ${calcLTV()} across the customer's LTV.
            </div>
          </div>
        </div>
      </div>


    </div>

  )


  function calcRoi () {
    let demosPerMonth = 15;
    let persifiMonthlyFees = 5000;

    let pipelineMonthly = demosPerMonth * ARRmonthly;



    let expectedRev = pipelineMonthly * convRate;



    let roi = expectedRev / 5000;
    let evOverCustomerLtv = LTVinMonths / expectedRev;

    return roi * 100;
  }


  function calcMRR () {
    let demosPerMonth = 15;
    let persifiMonthlyFees = 5000;

    let pipelineMonthly = demosPerMonth * ARRmonthly;



    let expectedRev = pipelineMonthly * convRate;



    let roi = expectedRev / 5000;
    let evOverCustomerLtv = LTVinMonths * expectedRev;

    return expectedRev;
  }

  function calcLTV () {
    let demosPerMonth = 15;
    let persifiMonthlyFees = 5000;

    let pipelineMonthly = demosPerMonth * ARRmonthly;



    let expectedRev = pipelineMonthly * convRate;



    let roi = expectedRev / 5000;
    let evOverCustomerLtv = LTVinMonths * expectedRev;

    return evOverCustomerLtv;
  }


}
